name: End-to-End Tests

on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        entry:
          - { os: ubuntu-latest, java: 11 }
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Set up SBT
        uses: sbt/setup-sbt@v1

      - name: Set SBT_OPTS
        # Needed to extend the JVM memory size to avoid OutOfMemoryError for HTML test report
        run: echo "SBT_OPTS=-Xmx2G" >> $GITHUB_ENV

      - name: Set environment variables
        # Set environment variables for GitHub Actions environment
        # Tests run on the GitHub runner and access Docker containers via port mapping
        run: |
          echo "S3_ENDPOINT=localhost" >> $GITHUB_ENV
          echo "S3_PORT=9000" >> $GITHUB_ENV
          echo "S3_REGION=us-east-1" >> $GITHUB_ENV
          # Use localhost for Spark host since tests run on the GitHub runner
          echo "SPARK_HOST=localhost" >> $GITHUB_ENV

      - name: Build project
        run: sbt assembly

      - name: Start Docker containers
        run: |
          cd docker/integ-test
          docker compose up -d
          echo "Waiting for services to start..."
          sleep 60
          docker ps -a

      - name: Check Docker container health
        run: |
          docker ps -a
          docker exec spark curl -s http://localhost:8080/ || echo "Spark master UI not available"
          docker exec minio-S3 curl -s http://localhost:9000/minio/health/live || echo "MinIO health check failed"
          docker exec opensearch curl -s -u admin:C0rrecthorsebatterystaple. http://localhost:9200/_cluster/health || echo "OpenSearch health check failed"

      - name: End-to-End Test
        run: |
          # Print environment for debugging
          echo "Current directory: $(pwd)"
          echo "Docker containers:"
          docker ps -a
          # Run the tests
          sbt e2etest/test

      - name: Capture Docker logs (on failure)
        if: failure()
        run: |
          docker ps -a
          docker logs opensearch > opensearch.log 2>&1 || true
          docker logs spark > spark.log 2>&1 || true
          docker logs minio-S3 > minio.log 2>&1 || true
          docker logs opensearch-dashboards > opensearch-dashboards.log 2>&1 || true
          docker logs spark-worker > spark-worker.log 2>&1 || true
          docker logs metastore > metastore.log 2>&1 || true

      - name: Upload Docker logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: docker-logs
          path: "*.log"

      - name: Upload test report
        if: always() # Ensures the artifact is saved even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/test-reports # Adjust this path if necessary