name: End-to-End Tests

on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Set up SBT
        uses: sbt/setup-sbt@v1

      - name: Build project
        run: sbt assembly

      - name: Create minimal docker-compose file
        run: |
          cd docker/integ-test
          cat > docker-compose.minimal.yml << 'EOF'
          services:
            metastore:
              image: apache/hive:3.1.3
              container_name: metastore
              environment:
                - SERVICE_NAME=metastore
              ports:
                - "9083:9083"
              networks:
                - test-network

            minio:
              image: minio/minio
              container_name: minio-S3
              command: server /data --console-address ":9001"
              ports:
                - "9000:9000"
                - "9001:9001"
              environment:
                - MINIO_ROOT_USER=minioadmin
                - MINIO_ROOT_PASSWORD=minioadmin
              networks:
                - test-network

            opensearch:
              image: opensearchproject/opensearch:latest
              container_name: opensearch
              environment:
                - discovery.type=single-node
                - bootstrap.memory_lock=true
                - DISABLE_SECURITY_PLUGIN=true
                - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
              ports:
                - "9200:9200"
              networks:
                - test-network

            spark:
              image: bitnami/spark:3.5.0
              container_name: spark
              hostname: spark
              environment:
                - SPARK_MODE=master
                - SPARK_RPC_AUTHENTICATION_ENABLED=no
                - SPARK_RPC_ENCRYPTION_ENABLED=no
                - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
                - SPARK_SSL_ENABLED=no
              ports:
                - "8080:8080"
                - "7077:7077"
                - "15002:15002"
              networks:
                - test-network

          networks:
            test-network:
          EOF

      - name: Start Docker containers
        run: |
          cd docker/integ-test
          docker compose -f docker-compose.minimal.yml up -d
          echo "Waiting for services to start..."
          sleep 60
          docker ps -a

      - name: Run tests with Docker
        run: |
          docker run --rm \
            --network $(docker network ls --format "{{.Name}}" | grep test-network) \
            -v $(pwd):/app \
            -w /app \
            -e SPARK_HOST=spark \
            -e S3_ENDPOINT=minio-S3 \
            -e OPENSEARCH_HOST=opensearch \
            -e GITHUB_ACTIONS=true \
            eclipse-temurin:11-jdk \
            bash -c "apt-get update && apt-get install -y curl && curl -L -o sbt.deb https://repo.scala-sbt.org/scalasbt/debian/sbt-1.9.8.deb && dpkg -i sbt.deb && rm sbt.deb && find . -name \"*.scala\" -type f -exec sed -i 's/[ \t]*$//' {} \; && JAVA_OPTS=\"-Xmx3g\" sbt -Dscalastyle.skip=true -Dtest.timefactor=3 e2etest/test"

      - name: Capture Docker logs (on failure)
        if: failure()
        run: |
          docker ps -a
          docker logs opensearch > opensearch.log 2>&1 || true
          docker logs spark > spark.log 2>&1 || true
          docker logs minio-S3 > minio.log 2>&1 || true

      - name: Upload Docker logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: docker-logs
          path: "*.log"
          if-no-files-found: warn

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/test-reports