name: End-to-End Tests

on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Set up SBT
        uses: sbt/setup-sbt@v1

      - name: Set SBT_OPTS
        # Needed to extend the JVM memory size to avoid OutOfMemoryError for HTML test report
        # Also skip scalastyle checks and increase test timeouts
        run: echo "SBT_OPTS=-Xmx3G -Dscalastyle.skip=true -Dtest.timefactor=3" >> $GITHUB_ENV

      - name: Set environment variables
        run: |
          echo "GITHUB_ACTIONS=true" >> $GITHUB_ENV
          echo "SPARK_HOST=localhost" >> $GITHUB_ENV
          echo "S3_ENDPOINT=localhost" >> $GITHUB_ENV
          echo "OPENSEARCH_HOST=localhost" >> $GITHUB_ENV

      - name: End-to-End Test
        run: sbt "e2etest/testOnly org.opensearch.spark.e2e.EndToEndTests"

      - name: Upload test report
        if: always() # Ensures the artifact is saved even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/test-reports # Adjust this path if necessary